spring:
  application:
    name: okten-java-springboot

  profiles:
    active: store1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-sender}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
    secret: wIsmGMq7PwPhXCP5MpU2xi6O8Yptziwm
    access-token:
      ttl-millis: 3600000
    refresh-token:
      ttl-millis: 360000000

mail:
  sender:
    username: ${mail-sender}